collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4767025
  brandStrength: 1
  lightness: 0.5089605
  brandColors:
    - '#383256'
    - '#F5E1D6'
    - '#92A7B8'
    - '#A3678B'
    - '#CE94AD'
  rhythmicContrast: 0.5573477
typography_spectrum: 0.1971326
layout_spectrum: 0.03225806
name: Ed Stevens
